version: "3.6"
services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  nuxt:
    build:
      context: ./
      dockerfile: Dockerfile.Nuxt
    ports:
      - "7000:7000"
      - "7001:7001"
    environment:
      NETWORK: "${NETWORK}"
      PROTOCOL: "${PROTOCOL}"
      DB_STRING_CONNECTION: "${DB_STRING_CONNECTION}"
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile.Proxy
      args:
        proxy_host: "${PROXY_HOST}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
volumes:
  mongo_data:
